import type { NextConfig } from 'next'

const securityHeaders = [
  { key: 'X-DNS-Prefetch-Control', value: 'on' },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=()',
  },
  {
    key: 'Content-Security-Policy',
    value: [
      "default-src 'self'",
      "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com",
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "font-src 'self' https://fonts.gstatic.com",
      "img-src 'self' data: blob: https://*.supabase.co https://www.google.com",
      "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.google-analytics.com https://*.sentry.io https://*.ingest.de.sentry.io",
      "frame-ancestors 'none'",
    ].join('; '),
  },
]

const oldBlogUrlRedirects = [
      { source: '/audi-s3-common-problems-uae', destination: '/blog/audi-s3-common-problems', permanent: true },
      { source: '/bmw-x1-common-problems-uae', destination: '/blog/bmw-x1-common-problems', permanent: true },
      { source: '/daewoo-cars-common-problems-uae', destination: '/blog/daewoo-cars-common-problems', permanent: true },
      { source: '/audi-q3-common-problems-uae', destination: '/blog/audi-q3-common-problems', permanent: true },
      { source: '/ford-ecosport-common-problems-uae', destination: '/blog/ford-ecosport-common-problems', permanent: true },
      { source: '/gmc-acadia-common-problems-uae', destination: '/blog/gmc-acadia-common-problems', permanent: true },
      { source: '/hyundai-accent-common-problems-uae', destination: '/blog/hyundai-accent-common-problems', permanent: true },
      { source: '/hyundai-tucson-common-problems-uae', destination: '/blog/hyundai-tucson-common-problems', permanent: true },
      { source: '/hyundai-cars-common-problems-uae', destination: '/blog/hyundai-cars-common-problems', permanent: true },
      { source: '/hyundai-i10-common-problems-uae', destination: '/blog/hyundai-i10-common-problems', permanent: true },
      { source: '/hyundai-veloster-common-problems-uae', destination: '/blog/hyundai-veloster-common-problems', permanent: true },
      { source: '/hummer-cars-common-problems-uae', destination: '/blog/hummer-cars-common-problems', permanent: true },
      { source: '/infiniti-cars-common-problems-uae', destination: '/blog/infiniti-cars-common-problems', permanent: true },
      { source: '/kia-rio-common-problems-uae', destination: '/blog/kia-rio-common-problems', permanent: true },
      { source: '/mazda-cx5-common-problems-uae', destination: '/blog/mazda-cx5-common-problems', permanent: true },
      { source: '/toyota-fortuner-common-problems-uae', destination: '/blog/toyota-fortuner-common-problems', permanent: true },
      { source: '/mitsubishi-lancer-common-problems-uae', destination: '/blog/mitsubishi-lancer-common-problems', permanent: true },
      { source: '/toyota-cars-common-problems-uae', destination: '/blog/toyota-cars-common-problems', permanent: true },
      { source: '/infiniti-qx80-common-problems-uae', destination: '/blog/infiniti-qx80-common-problems', permanent: true },
      { source: '/mg-zs-common-problems-uae', destination: '/blog/mg-zs-common-problems', permanent: true },
      { source: '/suzuki-jimny-common-problems-uae', destination: '/blog/suzuki-jimny-common-problems', permanent: true },
      { source: '/nissan-micra-common-problems-uae', destination: '/blog/nissan-micra-common-problems', permanent: true },
      { source: '/nissan-xtrail-common-problems-uae', destination: '/blog/nissan-xtrail-common-problems', permanent: true },
      { source: '/mitsubishi-outlander-common-problems-uae', destination: '/blog/mitsubishi-outlander-common-problems', permanent: true },
      { source: '/volvo-cars-common-problems-uae', destination: '/blog/volvo-cars-common-problems', permanent: true },
      { source: '/toyota-rav4-common-problems-uae', destination: '/blog/toyota-rav4-common-problems', permanent: true },
      { source: '/toyota-camry-common-problems-uae', destination: '/blog/toyota-camry-common-problems', permanent: true },
      { source: '/nissan-altima-common-problems-uae', destination: '/blog/nissan-altima-common-problems', permanent: true },
      { source: '/skoda-fabia-common-problems-uae', destination: '/blog/skoda-fabia-common-problems', permanent: true },
      { source: '/mg-cars-common-problems-uae', destination: '/blog/mg-cars-common-problems', permanent: true },
      { source: '/mitsubishi-cars-common-problems-uae', destination: '/blog/mitsubishi-cars-common-problems', permanent: true },
      { source: '/blown-car-gasket', destination: '/blog/blown-car-gasket', permanent: true },
      { source: '/car-wont-start', destination: '/blog/car-wont-start', permanent: true },
      { source: '/oil-leaking-from-car', destination: '/blog/oil-leaking-from-car', permanent: true },
      { source: '/gear-oil-leak', destination: '/blog/gear-oil-leak', permanent: true },
      { source: '/car-overheating', destination: '/blog/car-overheating', permanent: true },
      { source: '/darb-toll-gate-registration-online', destination: '/blog/darb-toll-gate-registration-online', permanent: true },
      { source: '/lost-plate-number-dubai', destination: '/blog/lost-plate-number-dubai', permanent: true },
      { source: '/s-gear-in-automatic-cars', destination: '/blog/s-gear-in-automatic-cars', permanent: true },
      { source: '/salik-recharge-online', destination: '/blog/salik-recharge-online', permanent: true },
      { source: '/traffic-fine-discount-dubai', destination: '/blog/traffic-fine-discount-dubai', permanent: true },
      { source: '/electric-car-problems', destination: '/blog/electric-car-problems', permanent: true },
      { source: '/car-logos-meaning', destination: '/blog/car-logos-meaning', permanent: true },
      { source: '/car-warning-lights', destination: '/blog/car-warning-lights', permanent: true },
      { source: '/car-shuts-off-while-driving', destination: '/blog/car-shuts-off-while-driving', permanent: true },
      { source: '/check-salik-balance', destination: '/blog/check-salik-balance', permanent: true },
      { source: '/car-not-going-into-gear', destination: '/blog/car-not-going-into-gear', permanent: true },
      { source: '/car-garage-dubai', destination: '/blog/car-garage-dubai', permanent: true },
      { source: '/idle-air-control-valve', destination: '/blog/idle-air-control-valve', permanent: true },
      { source: '/audi-epc-light-on', destination: '/blog/audi-epc-light-on', permanent: true },
      { source: '/radiator-fluid-leak', destination: '/blog/radiator-fluid-leak', permanent: true },
      { source: '/engine-oil-light-on', destination: '/blog/engine-oil-light-on', permanent: true },
      { source: '/car-emission-system-problem', destination: '/blog/car-emission-system-problem', permanent: true },
      { source: '/car-engine-misfire-causes-symptoms', destination: '/blog/car-engine-misfire-causes-symptoms', permanent: true },
      { source: '/bmw-check-engine-light', destination: '/blog/bmw-check-engine-light', permanent: true },
      { source: '/car-vibration-at-high-speeds', destination: '/blog/car-vibration-at-high-speeds', permanent: true },
      { source: '/steering-wheel-vibration-when-braking', destination: '/blog/steering-wheel-vibration-when-braking', permanent: true },
      { source: '/head-gasket-repair-cost', destination: '/blog/head-gasket-repair-cost', permanent: true },
      { source: '/car-shaking-at-idle', destination: '/blog/car-shaking-at-idle', permanent: true },
      { source: '/black-smoke-from-exhaust', destination: '/blog/black-smoke-from-exhaust', permanent: true },
      { source: '/bad-starter-symptoms', destination: '/blog/bad-starter-symptoms', permanent: true },
      { source: '/bad-fuel-injector', destination: '/blog/bad-fuel-injector', permanent: true },
      { source: '/blown-head-gasket', destination: '/blog/blown-head-gasket', permanent: true },
      { source: '/6.4-powerstroke-problems', destination: '/blog/6.4-powerstroke-problems', permanent: true },
      { source: '/car-battery-problems', destination: '/blog/car-battery-problems', permanent: true },
      { source: '/car-alternator-problems', destination: '/blog/car-alternator-problems', permanent: true },
      { source: '/car-charging-port-not-working', destination: '/blog/car-charging-port-not-working', permanent: true },
      { source: '/car-ac-not-blowing-cold-air', destination: '/blog/car-ac-not-blowing-cold-air', permanent: true },
      { source: '/car-engine-problems', destination: '/blog/car-engine-problems', permanent: true },
      { source: '/car-belt-noise', destination: '/blog/car-belt-noise', permanent: true },
      { source: '/car-humming-noise', destination: '/blog/car-humming-noise', permanent: true },
      { source: '/car-clicking-and-not-starting', destination: '/blog/car-clicking-and-not-starting', permanent: true },
      { source: '/why-is-my-car-burning-oil', destination: '/blog/why-is-my-car-burning-oil', permanent: true },
      { source: '/locked-my-keys-in-my-car', destination: '/blog/locked-my-keys-in-my-car', permanent: true },
      { source: '/car-gearbox-problems', destination: '/blog/car-gearbox-problems', permanent: true },
      { source: '/fujairah-to-dubai', destination: '/blog/fujairah-to-dubai', permanent: true },
      { source: '/abu-dhabi-to-dubai-by-bus', destination: '/blog/abu-dhabi-to-dubai-by-bus', permanent: true },
      { source: '/ras-al-khaimah-to-dubai', destination: '/blog/ras-al-khaimah-to-dubai', permanent: true },
      { source: '/sharjah-to-dubai', destination: '/blog/sharjah-to-dubai', permanent: true },
      { source: '/ajman-to-dubai', destination: '/blog/ajman-to-dubai', permanent: true },
      { source: '/abu-dhabi-taxi-fare', destination: '/blog/abu-dhabi-taxi-fare', permanent: true },
      { source: '/umm-al-quwain-to-dubai', destination: '/blog/umm-al-quwain-to-dubai', permanent: true },
      { source: '/dubai-taxi-fare', destination: '/blog/dubai-taxi-fare', permanent: true },
      { source: '/sharjah-taxi-fare', destination: '/blog/sharjah-taxi-fare', permanent: true },
      { source: '/dubai-metro', destination: '/blog/dubai-metro', permanent: true },
      { source: '/al-jadaf-metro-station-dubai-the-locals-guide-you-need-in-2025', destination: '/blog/al-jadaf-metro-station-dubai-the-locals-guide-you-need', permanent: true },
      { source: '/adcb-metro-station-dubai-the-locals-guide-you-need-in-2025', destination: '/blog/adcb-metro-station-dubai-the-locals-guide-you-need', permanent: true },
      { source: '/al-nahda-metro-station-dubai-your-local-guide-for-2025', destination: '/blog/al-nahda-metro-station-dubai-your-local-guide', permanent: true },
      { source: '/al-qiyadah-metro-station-dubai-your-local-guide-to-timings-tips-2025', destination: '/blog/al-qiyadah-metro-station-dubai-your-local-guide-to-timings-tips', permanent: true },
      { source: '/al-ras-metro-station-dubai-your-essential-guide-to-old-dubais-gateway', destination: '/blog/al-ras-metro-station-dubai-your-essential-guide-to-old-dubais-gateway', permanent: true },
      { source: '/dubai-internet-city-metro-station', destination: '/blog/dubai-internet-city-metro-station', permanent: true },
      { source: '/toyota-corolla-problems', destination: '/blog/toyota-corolla-problems', permanent: true },
      { source: '/ford-f-150-common-problems', destination: '/blog/ford-f-150-common-problems', permanent: true },
      { source: '/dodge-ram-1500', destination: '/blog/dodge-ram-1500-common-problems', permanent: true },
      { source: '/lexus-lx-570-common-problems', destination: '/blog/lexus-lx-570-common-problems', permanent: true },
] as const

const nextConfig: NextConfig = {
  async redirects() {
    return [...oldBlogUrlRedirects]
  },
  async headers() {
    return [
      { source: '/:path*', headers: securityHeaders },
      {
        source: '/api/:path*',
        headers: [{ key: 'X-Robots-Tag', value: 'noindex, nofollow' }],
      },
    ]
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '*.supabase.co' },
      { protocol: 'https', hostname: 'www.google.com' },
    ],
  },
}

export default nextConfig
